import { TFood } from "components/Food/types";
import FoodImage1 from "assets/img/food-card-image-1.png";
import FoodImage2 from "assets/img/food-card-image-2.png";
import RestaurantImage from "assets/img/restaurant1.jpg";
import { TRestaurant } from "components/Restaurant/types";

export const restaurants : TRestaurant[] = [
    {
        id: 0,
        name: "Fast Food X",
        categories: ["Cake", "Bread"],
        distance: 1.8,
        openAt: "10:00 AM",
        rate: 4.3,
        picture: RestaurantImage,
        closed: false,
    },
    {
        id: 1,
        name: "Fast Food X",
        categories: ["Cake", "Bread"],
        distance: 1.8,
        openAt: "10:00 AM",
        rate: 4.3,
        picture: RestaurantImage,
        closed: true,
    },
    {
        id: 2,
        name: "Fast Food X",
        categories: ["Cake", "Bread"],
        distance: 1.8,
        openAt: "10:00 AM",
        rate: 4.3,
        picture: RestaurantImage,
        closed: true,
    },
    {
        id: 3,
        name: "Fast Food X",
        categories: ["Cake", "Bread"],
        distance: 1.8,
        openAt: "10:00 AM",
        rate: 4.3,
        picture: RestaurantImage,
        closed: false,
    },
    {
        id: 4,
        name: "Fast Food X",
        categories: ["Cake", "Bread"],
        distance: 1.8,
        openAt: "10:00 AM",
        rate: 4.3,
        picture: RestaurantImage,
        closed: false,
    },
];

export const foods: TFood[] = [
    {
        id: 43,
        name: "Salmon & Leek Dumplings",
        price: 26,
        discount: 30,
        rate: 4,
        orderTime: 45,
        picture: FoodImage1,
        restaurant: 2343,
    },
    {
        id: 234,
        name: "Hamburger",
        price: 30,
        rate: 4.8,
        orderTime: 25,
        picture: FoodImage2,
        restaurant: 2343,
    },
    {
        id: 54,
        name: "Hotdog",
        price: 42,
        discount: 45,
        rate: 3.9,
        orderTime: 28,
        picture: FoodImage1,
        restaurant: 2343,
    },
    {
        id: 75,
        name: "Chicken Burger",
        price: 26,
        discount: 30,
        rate: 4,
        orderTime: 45,
        picture: FoodImage2,
        restaurant: 2343,
    },
    {
        id: 5,
        name: "Cheese Burger",
        price: 42,
        discount: 45,
        rate: 3.9,
        orderTime: 28,
        picture: FoodImage1,
        restaurant: 2343,
    },
    {
        id: 6,
        name: "Grilled Fish",
        price: 26,
        discount: 30,
        rate: 4,
        orderTime: 45,
        picture: FoodImage1,
        restaurant: 2343,
    },
];
